# Generated by Django 5.2 on 2025-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(max_length=10)),
                ('book_author', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=100)),
            ],
        ),
    ]
