# Generated by Django 5.2 on 2025-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='addbook',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='addbook',
            name='book_title',
        ),
        migrations.AddField(
            model_name='addbook',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
        migrations.AddField(
            model_name='addbook',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=255),
        ),
    ]
